### PR TITLE
fixed usage of key with CKA_ALWAYS_AUTHENTICATE

### PR DESCRIPTION
**Pull request by frankmorgner**
See NSS for reference
(https://github.com/mozilla/gecko/blob/55f00b0e760d07f94fe9ff534d6ee39542567f95/security/nss/lib/pk11wrap/pk11obj.c#L830-L835),
which instructs PK11_DoPassword to do a context specific login in case
of the CKA_ALWAYS_AUTHENTICATE attribute set.

### CODE REVIEW

**Comment by jsha** [comment]
Thanks for the PR! I'm planning to take a look at this this week.

**Comment by jsha** [comment]
This looks good, and the reference checks out. Do you have an example of a device that fails before this change and works afterwards? Ideally I'd like to include that as part of the description of the PR.

**Comment by frankmorgner** [comment]
As stated [here](https://github.com/letsencrypt/pkcs11key/issues/19), a yubikey with a PIV slot that always requires the PIN will now work with OpenSC.

**Comment by jsha** [comment]
I'm unable to reproduce the problem. Here's the command I'm using (running in the `pkcs11key/v3` directory):

```
$ ykman piv generate-key --algorithm ECCP256 --pin-policy ALWAYS --touch-policy ALWAYS 9a pubkey.pem && ykman piv generate-certificate --subject "yubico" 9a pubkey.pem && ykman piv export-certificate 9a cert.pem && go test -bench=. -module /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so -pin 123456 -cert cert.pem -tokenLabel yubico
Enter a management key [blank to use default key]: 
Enter PIN: 
Enter a management key [blank to use default key]: 
Touch your YubiKey...
unrecognized search:
  Type: 0, Value: 0200000000000000
  Type: 100, Value: 0000000000000000
  Type: 120, Value: 02
  Type: 122, Value: 02
goos: linux
goarch: amd64
pkg: github.com/letsencrypt/pkcs11key/v3
BenchmarkPKCS11-12             1        3777301537 ns/op
--- BENCH: BenchmarkPKCS11-12
    pkcs11key_bench_test.go:125: Time, count, ops / second: 3.777154673s, 1, 0.26474955001134526
PASS
ok      github.com/letsencrypt/pkcs11key/v3     3.976s
```

Here's my YubiKey info:
```
$ ykman info
Device type: YubiKey 4
Serial number: 4678463
Firmware version: 4.3.1
Enabled USB interfaces: OTP+FIDO+CCID

Applications
OTP             Enabled         
FIDO U2F        Enabled         
OpenPGP         Enabled         
PIV             Enabled         
OATH            Enabled         
FIDO2           Not available   
```

Can you share the corresponding info from your key, and test output?

**Comment by frankmorgner** [comment]
I stumbled upon this problem while using https://github.com/square/ghostunnel...

**Comment by jsha** [comment]
I'm going to go ahead and merge this, since it is correct according to the PKCS#11 specs, and I've tested that it doesn't break on my Yubikey. @frankmorgner, I'd still love to see the output of `ykman info` for your device, and detailed reproduction instruction, so I can verify the fix.

Thanks,
Jacob

**Pull request merged**
