### PR TITLE
Use RFC 5480 output format for ECDSA (and bump release)

### PR DESCRIPTION
**Pull request by csstaub**
Two changes in this pull request: (1) I copied the files from v3 over into v4 to bump the release, and (2) updated the ECDSA code to use the RFC 5480 output format (fixes issue #18). I split these up into two different commits to make it easier to review.

Verified this works with Ghostunnel integration tests, using ECDSA keys, to handshake a TLS 1.3 connection with OpenSSL/SoftHSMv2.

r: @jsha @rolandshoemaker @cpu

### CODE REVIEW

**Comment by jsha** [comment]
Thanks for the PR! I'm planning to take a look at it this week.

**Comment by rolandshoemaker** [comment]
(Just so that we don't forget, when this merges we'll want to push a `v4.0.0` tag)

**Comment by csstaub** [comment]
Done, removed the old `v3` directory @jsha.

**Comment by jsha** [comment]
I'm going to hold off on merging this till https://github.com/letsencrypt/pkcs11key/pull/24 lands, so we can wrap both changes into a v4.0.0 release. That means I'll wind up asking you for one more merge from master - sorry for the inconvenience!

**Comment by jsha** [comment]
Changed my mind - since this is ready to go and #24 is not quite ready, I'm going to merge this now. I'll just hold off on tagging v4.0.0 until #24 is also landed.

**Pull request merged**
